config/routes.rb
Rails.application.routes.draw do
  resources :podcasts
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/podcast.rb
class Podcast < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/podcasts_controller.rb
class PodcastsController < ApplicationController
  before_action :set_podcast, only: [:show, :edit, :update, :destroy]
  before_action :set_s3_direct_post, only: [:new, :edit, :create, :update]

  # GET /podcasts
  # GET /podcasts.json
  def index
    @podcasts = Podcast.all
  end

  # GET /podcasts/1
  # GET /podcasts/1.json
  def show
  end

  # GET /podcasts/new
  def new
    @podcast = Podcast.new
  end

  # GET /podcasts/1/edit
  def edit
  end

  # POST /podcasts
  # POST /podcasts.json
  def create
    @podcast = Podcast.new(podcast_params)

    respond_to do |format|
      if @podcast.save
        format.html { redirect_to @podcast, notice: 'Podcast was successfully created.' }
        format.json { render :show, status: :created, location: @podcast }
      else
        format.html { render :new }
        format.json { render json: @podcast.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /podcasts/1
  # PATCH/PUT /podcasts/1.json
  def update
    respond_to do |format|
      if @podcast.update(podcast_params)
        format.html { redirect_to @podcast, notice: 'Podcast was successfully updated.' }
        format.json { render :show, status: :ok, location: @podcast }
      else
        format.html { render :edit }
        format.json { render json: @podcast.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /podcasts/1
  # DELETE /podcasts/1.json
  def destroy
    @podcast.destroy
    respond_to do |format|
      format.html { redirect_to podcasts_url, notice: 'Podcast was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    def set_s3_direct_post
      @s3_direct_post = S3_BUCKET.presigned_post(key: "uploads/#{SecureRandom.uuid}/${filename}", success_action_status: '201', acl: 'public-read')
    end
    # Use callbacks to share common setup or constraints between actions.
    def set_podcast
      @podcast = Podcast.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def podcast_params
      params.require(:podcast).permit(:episode_title, :episode_description, :image_url, :episode_url)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/podcasts_helper.rb
module PodcastsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DirectS3Example</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/podcasts/_form.html.erb
<%= form_for(@podcast, html: { class: 'directUpload', data: { 'form-data' => (@s3_direct_post.fields), 'url' => @s3_direct_post.url, 'host' => URI.parse(@s3_direct_post.url).host } }) do |f| %>
  <% if podcast.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(podcast.errors.count, "error") %> prohibited this podcast from being saved:</h2>

      <ul>
      <% podcast.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :episode_title %>
    <%= f.text_field :episode_title %>
  </div>

  <div class="field">
    <%= f.label :episode_description %>
    <%= f.text_field :episode_description %>
  </div>

  <div class="field">
    <%= f.label :image_url %>
    <%= f.file_field :image_url %>
  </div>

  <div class="field">
    <%= f.label :episode_url %>
    <%= f.file_field :episode_url %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>


<script>
$(function() {
  $('.directUpload').find("input:file").each(function(i, elem) {
    var fileInput    = $(elem);
    var form         = $(fileInput.parents('form:first'));
    var submitButton = form.find('input[type="submit"]');
    var progressBar  = $("<div class='bar'></div>");
    var barContainer = $("<div class='progress'></div>").append(progressBar);
    var fd           = $(elem);
    fileInput.after(barContainer);
    fileInput.fileupload({ 
      // add: function (e, data) {
      //   fd["Content-Type"] = data.files[0].type;  
      //   data.formData = fd;
      //   console.log(fd["Content-Type"]);
      //   data.submit();
      // }, 
      fileInput:       fileInput,
      url:             form.data('url'),
      type:            'POST',
      autoUpload:       true,
      formData:         form.data('form-data'),
      paramName:        'file', // S3 does not like nested name fields i.e. name="user[avatar_url]"
      dataType:         'XML',  // S3 returns XML if success_action_status is set to 201
      replaceFileInput: false,
      progressall: function (e, data) {
        var progress = parseInt(data.loaded / data.total * 100, 10);
        progressBar.css('width', progress + '%')
      },
      start: function (e) {
        submitButton.prop('disabled', true);
        progressBar.
          css('background', 'green').
          css('display', 'block').
          css('width', '0%').
          text("Loading...");
      },
      done: function(e, data) {
        submitButton.prop('disabled', false);
        progressBar.text("Uploading done");
        // extract key and generate URL from response
        var key   = $(data.jqXHR.responseXML).find("Key").text();
        var url   = '//' + form.data('host') + '/' + key;
        console.log(url);
        
        var input = $("<input />", { type:'hidden', name: fileInput.attr('name'), value: url })
        form.append(input);
      },
      fail: function(e, data) {
        submitButton.prop('disabled', false);
        progressBar.
          css("background", "red").
          text("Failed");
      }
    });
  });
});
</script>

app/views/podcasts/edit.html.erb
<h1>Editing Podcast</h1>

<%= render 'form', podcast: @podcast %>

<%= link_to 'Show', @podcast %> |
<%= link_to 'Back', podcasts_path %>

app/views/podcasts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Podcasts</h1>

<table>
  <thead>
    <tr>
      <th>Episode title</th>
      <th>Episode description</th>
      <th>Image url</th>
      <th>Episode url</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @podcasts.each do |podcast| %>
      <tr>
        <td><%= podcast.episode_title %></td>
        <td><%= podcast.episode_description %></td>
        <td><%= podcast.image_url %></td>
        <td><%= podcast.episode_url %></td>
        <td><%= link_to 'Show', podcast %></td>
        <td><%= link_to 'Edit', edit_podcast_path(podcast) %></td>
        <td><%= link_to 'Destroy', podcast, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Podcast', new_podcast_path %>

app/views/podcasts/new.html.erb
<h1>New Podcast</h1>

<%= render 'form', podcast: @podcast %>

<%= link_to 'Back', podcasts_path %>

app/views/podcasts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Episode title:</strong>
  <%= @podcast.episode_title %>
</p>

<p>
  <strong>Episode description:</strong>
  <%= @podcast.episode_description %>
</p>

<%= image_tag @podcast.image_url %>

<%= audio_tag @podcast.episode_url, controls: true, autoplay: false %>

<p>
  <strong>Image url:</strong>
  <%= @podcast.image_url %>
</p>

<p>
  <strong>Episode url:</strong>
  <%= @podcast.episode_url %>
</p>

<%= link_to 'Edit', edit_podcast_path(@podcast) %> |
<%= link_to 'Back', podcasts_path %>

app/views/users/_form.html.erb
<%= form_for(@user, html: { class: 'directUpload', data: { 'form-data' => (@s3_direct_post.fields), 'url' => @s3_direct_post.url, 'host' => URI.parse(@s3_direct_post.url).host } }) do |f| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %>
    <%= f.text_field :podcast_title %>
  </div>

  <div class="field">
    <%= f.label :description %>
    <%= f.text_area :name %>
  </div>

  <div class="field">
    <%= f.label :image %>
    <%= f.file_field :avatar_url %>
  </div>

  <div class="field">
    <%= f.label :podcast %>
    <%= f.file_field :podcast_url %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>



<script>
$(function() {
  $('.directUpload').find("input:file").each(function(i, elem) {
    var fileInput    = $(elem);
    var form         = $(fileInput.parents('form:first'));
    var submitButton = form.find('input[type="submit"]');
    var progressBar  = $("<div class='bar'></div>");
    var barContainer = $("<div class='progress'></div>").append(progressBar);
    var fd           = $(elem);
    fileInput.after(barContainer);
    fileInput.fileupload({ 
      // add: function (e, data) {
      //   fd["Content-Type"] = data.files[0].type;  
      //   data.formData = fd;
      //   console.log(fd["Content-Type"]);
      //   data.submit();
      // }, 
      fileInput:       fileInput,
      url:             form.data('url'),
      type:            'POST',
      autoUpload:       true,
      formData:         form.data('form-data'),
      paramName:        'file', // S3 does not like nested name fields i.e. name="user[avatar_url]"
      dataType:         'XML',  // S3 returns XML if success_action_status is set to 201
      replaceFileInput: false,
      progressall: function (e, data) {
        var progress = parseInt(data.loaded / data.total * 100, 10);
        progressBar.css('width', progress + '%')
      },
      start: function (e) {
        submitButton.prop('disabled', true);
        progressBar.
          css('background', 'green').
          css('display', 'block').
          css('width', '0%').
          text("Loading...");
      },
      done: function(e, data) {
        submitButton.prop('disabled', false);
        progressBar.text("Uploading done");
        // extract key and generate URL from response
        var key   = $(data.jqXHR.responseXML).find("Key").text();
        var url   = '//' + form.data('host') + '/' + key;
        console.log(url);
        
        var input = $("<input />", { type:'hidden', name: fileInput.attr('name'), value: url })
        form.append(input);
      },
      fail: function(e, data) {
        submitButton.prop('disabled', false);
        progressBar.
          css("background", "red").
          text("Failed");
      }
    });
  });
});
</script>